export const AUTH_TYPES = {
  SIGN_UP_FAILURE: 'SING_UP_FAILURE',
  SET_AUTH_USER: 'SET_AUTH_USER',
  LOG_OUT_USER: 'lOG_OUT_USER',
  FETCH_USER_DATA: 'FETCH_USER_DATA',
  SET_AUTH_LOGIN_ERROR: 'SET_AUTH_LOGIN_ERROR',
  SET_AUTH_REGISTER_ERROR: 'SET_AUTH_REGISTER_ERROR',
  AUTH_START: 'AUTH_START',
  FETCH_USER_DATA_START: 'FETCH_USER_DATA_START',
  FETCH_USER_DATA_END: 'FETCH_USER_DATA_END',
  FETCH_BOOKMARKS: 'FETCH_BOOKMARKS',
};
